apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manga-app
  labels:
    app: manga-app
spec:
  selector:
    matchLabels:
      app: manga-app
      tier: web
  template:
    metadata:
      labels:
        app: manga-app
        tier: web
        sha: ${SHORT_SHA}
    spec:
      containers:
        - name: manga-app
          image: gcr.io/website-227817/manga-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: manga-app
  labels:
    app: manga-app
spec:
  type: NodePort
  selector:
    app: manga-app
    tier: web
  ports:
    - port: 4000
      targetPort: 4000
